chat/urls.py
from django.urls import path
from .views import index, room

app_name = 'chat'

urlpatterns = [
    path("", index, name="index"),
    path("<str:room_name>/", room, name="room")
]




core/urls.py
from django.urls import path, include, re_path
from .views import index, About, Contact, Terms, FAQ, Receive, Send, Banks, NewCard, NewBank, Transactions, profile, buy_request, Withdraw, sell_request, Notifications, delete_notification, detail_notification, delete_card, delete_bank

app_name = 'core'

urlpatterns = [

    path('', index, name='index'),
    path('about/', About.as_view(), name='about'),
    path('contact/', Contact.as_view(), name='contact'),
    path('terms/', Terms.as_view(), name='terms'),
    path('faq/', FAQ.as_view(), name='faq'),

    # User Profile Settings
    path('settings/', profile, name='settings'),

    # Send & Receive
    path('receive/', Receive, name='receive'),
    path('send/', Send, name='send'),
    path('transactions/', Transactions, name='transactions'),
    path('withdraw/', Withdraw, name='withdraw'),

    # Notification Session
    path('notifications/', Notifications, name='notifications'),
    re_path('^delete/(?P<pk>[0-9]+)/$', delete_notification, name='delete_notification'),
    re_path('^detail/(?P<pk>[0-9]+)/$', detail_notification, name='detail_notification'),

    # Bank Accounts
    path('linked_accounts/', Banks, name='cards&banks'),
	path('add_card/', NewCard, name='add_card'),
    re_path('^delete_card/(?P<pk>[0-9]+)/$', delete_card, name='delete_card'),
	path('add_bank/', NewBank.as_view(), name='add_bank'),
    re_path('^delete_bank/(?P<pk>[0-9]+)/$', delete_bank, name='delete_bank'),

    # Buy Bitcoin Request
    path('buy_request/', buy_request, name="buy_request"),
    path('sell_request/', sell_request, name="sell_request"),
]

escrowlite/urls.py

from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('trade/', include('trade.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models
from core.choices import currencyChoices, paymentMethodChoices

class Room(models.Model):
    
    name = models.CharField(max_length=20)

    currency = models.CharField(max_length=100, choices=currencyChoices)
    purchase_price = models.FloatField()
    btc_price = models.FloatField()
    rate = models.FloatField()
    method = models.CharField(max_length=250, choices=paymentMethodChoices, null=True)
    terms = models.CharField(max_length=300)
    time = models.IntegerField()
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return self.name


    # def get_recent_messages(self):
    #     return self.messages_set.all().order_by('-timestamp')[:10]


class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    image = models.FileField(upload_to='media', blank=True)

    class Meta:
        ordering = ('timestamp',)

    def __str__(self):
        return self.author.username



chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import login_required
from .models import Room, Message
import json


def index(request):
    
    return render(request, "chat/index.html")


@login_required
def room(request, room_name):
    """
    Chat Room View
    """
    Room.objects.get_or_create(name=room_name)

    room = Room.objects.get(name=room_name)
    messages = room.message_set.all()

    # Sniff Out The Registered Users To Room
    active_users = []
    for msg in messages:
        user = msg.author.username       
        if user not in active_users:
            active_users.append(user)


    context = {
        'room': room,
        'users': mark_safe(active_users),
        'Usernames': active_users,
        'room_name_json': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.user.username)),
    }

    return render(request, 'chat/room.html', context)

chat/templates/chat/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>EscrowLite</title>
	<meta charset="UTF-8">
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>
    <script src="https://use.typekit.net/hoy3lrg.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" />

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section clearfix">
		<div class="container-fluid">
			<a href="{% url 'core:index' %}" class="site-logo">
				<img src="{% static 'core/img/escrow1.png' %}" alt="">
			</a>
			<div class="responsive-bar"><i class="fa fa-bars"></i></div>
			<a href="" class="user"><i class="fa fa-user"></i></a>
			{% if user.is_authenticated %}
			<a href="{% url 'account_logout' %}" class="site-btn btn-info">Log Out</a>
			<a href="{% url 'account_email' %}" class="site-btn">Buy bitcoins</a>
			<a href="{% url 'account_email' %}" class="site-btn">Sell bitcoins</a>
			<nav class="main-menu">
				<ul class="menu-list">
					<li><a href="{% url 'core:contact' %}">Help</a></li>
				</ul>
			</nav>
			{% else %}
			<a href="{% url 'account_signup' %}" class="site-btn btn-info">Sign Up Free</a>
			<a href="{% url 'account_login' %}" class="site-btn">Log In</a>
			<nav class="main-menu">
				<ul class="menu-list">
					<li><a href="{% url 'core:index' %}">Home</a></li>
					<li><a href="{% url 'core:about' %}">About</a></li>
					<li><a href="">FAQ</a></li>
					<li><a href="{% url 'core:contact' %}">Contact</a></li>
				</ul>
			</nav>
			{% endif %}
		</div>
	</header>
	
	{% block content %}
	{% endblock content %}

	<!-- Newsletter section -->
	<section class="newsletter-section gradient-bg">
		<div class="container text-white">
			<div class="row">
				<div class="col-lg-7 newsletter-text">
					<h2>Subscribe to our Newsletter</h2>
					<p>Sign up for our weekly industry updates, insider perspectives and in-depth market analysis.</p>
				</div>
				<div class="col-lg-5 col-md-8 offset-lg-0 offset-md-2">
					<form class="newsletter-form">
						<input type="text" placeholder="Enter your email">
						<button>Get Started</button>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="footer-bottom">
				<div class="row">
					<div class="col-md-6 col-lg-3 footer-widget">
						<img src="{% static 'core/img/logo.png' %}" class="mb-4" alt="">
						<span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	Copyright &copy;<script>document.write(new Date().getFullYear());</script> EscrowLite | All rights reserved 
	<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
					</div>
					<div class="col-lg-8 text-center text-lg-right">
						<ul class="footer-nav">
							<li><a href="{% url 'core:terms' %}">Terms of Use</a></li>
							<li><a href="{% url 'core:terms' %}">Privacy Policy </a></li>
							<li><a href="">support@company.com</a></li>
							<li><a href="">(123) 456-7890</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>


	<!--====== Javascripts & Jquery ======-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'core/assets/js/jquery.payform.min.js' %}" charset="utf-8"></script>
    <script src="{% static 'core/assets/js/script.js' %}"></script>
	<script src="{% static 'core/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'core/js/owl.carousel.min.js' %}"></script>

</body>
</html>

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>
    <script src="https://use.typekit.net/hoy3lrg.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>

<body>

<div id="frame">
  <div id="sidepanel">
    <div id="profile">
      <div class="wrap">
        <h2>Escrow Lite Trade</h2>
        <hr>
      </div>
    </div>
    <div id="search">
      <label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
      <input type="text" placeholder="Search contacts..." />
    </div>
    <div id="contacts">
      <ul>
        <h4>Active Users</h4>
        <hr>
        {% for user in Usernames %}
        <li class="contact">
          <div class="wrap">
            <!-- {% comment %} <img src="http://emilcarlsson.se/assets/louislitt.png" alt="" /> {% endcomment %} -->
            <div class="meta">
              <span class="contact-status online"></span>
              <p class="name" id="active_user">{{ user }}</p>
              <!-- {% comment %} <p class="preview">You just got LITT up, Mike.</p> {% endcomment %} -->
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div id="bottom-bar">
      <a href="#" id="paid_trade" onclick="ConfirmPayment()"><button><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i><span> Mark As Paid</span></button></a>
      <a href="#" id="cancel_trade" onclick="CancelTrade()"><button class="btn-light"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span> Cancel Trade</span></button></a>
    </div>
  </div>
  <div class="content">
    <div class="contact-profile text-center">
      <h4>Buying <b>{{ room.btc_price }}</b> BTC for <b>{{ room.purchase_price }}</b> {{ room.currency }} @ <b>{{ room.rate }}</b> {{ room.currency }}/BTC</h4> {% endcomment %}
      <h4>Method: {{ room.method }} <b></b> </h4>
    </div>
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 text-left">
          <p><b>Instructions & Terms : {{ room.terms }}</b></p>
          <div class="social-media">  
             <h7>Dispute in <button id="dispute" onclick="" class="site-btn btn-danger"><span id="time">05:00</span></button></h7>
          </div>
        </div>
        <div class="col-lg-4 text-center">
          <div id="status" class="jumbotron bg-secondary p-1">
            <h4><b id="confirmationText">Awaiting Payment Confirmation</b></h4>
          </div>
        </div>
      </div>

    </div>
    <div class="messages">
      <ul id="chat-log">
      </ul>
    </div>
    <div class="message-input">
      <div class="wrap">
        <input id="chat-message-input" name="message" type="text" placeholder="Write your message..." />
        
        <!-- <a onclick='SwitchToImage()'>Upload</a> -->
          
        <input type="file" name="id_image" enctype="multipart/form-data" id="id_image">
        <button id="chat-message-submit" type="submit" class="submit">
          <i class="fa fa-paper-plane" aria-hidden="true"></i>
        </button>

      </div>
    </div>
  </div>
</div>

<script src="{% static 'main.js' %}"></script>
<script src="{% static 'reconnecting-websocket.js' %}"></script>
<script>
    var roomName = {{ room_name_json }};
    var username = {{ username }};
    var users = {{ users }};

    var notNewUser = users.includes(String(username));

    function startTimer(duration, display) {
        var timer = duration, minutes, seconds;
        setInterval(function () {
            minutes = parseInt(timer / 60, 10);
            seconds = parseInt(timer % 60, 10);

            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.textContent = minutes + ":" + seconds;

            window.minutesLeft = minutes;
            window.secondsLeft = seconds;

            if (--timer < 0) {
                timer = duration;
            }
        }, 1000);
    }


    // {% comment %} window.onload = function () {
    //     var Minutes = 60 * Integer(window.minutesLeft),
    //         display = document.querySelector('#time');
    //     startTimer(Minutes, display);
    // }; {% endcomment %}

    var chatSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onopen = function(e) {
      if (notNewUser === true) {
        fetchMessages();
      } else {
        // joinChat();
        users.push(String(username));
        fetchMessages();
      };
    }

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        console.log(data);

        if (data['command'] === 'messages') {
          for (let i=0; i<data['messages'].length; i++) {
            createMessage(data['messages'][i]);
          }
        } else if (data['command'] === 'new_message'){
          createMessage(data['message']);
        };
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.getElementById('chat-message-input');
        var imageInputDom = document.getElementById('id_image');
        console.log(imageInputDom.value)

        if (imageInputDom.value === "") {
          var image = null;
        } else {
          var image = URL.createObjectURL(imageInputDom.files[0]);
        }
        
        console.log(image)
        var message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'image' : image,
            'from': username,
            'room': roomName,
            'min-timer' : window.minutesLeft,
            'sec-timer' : window.secondsLeft,
        }));

        messageInputDom.value = '';
        imageInputDom.value = '';
        window.scrollTo(0, document.body.scrollHeight);

        var Minutes = 60 * {{ room.time }};
        
        display = document.querySelector('#time');
        display.value = '';
        startTimer(Minutes, display);
    };

    function fetchMessages() {
      chatSocket.send(JSON.stringify({
        'command': 'fetch_messages',
        'room': roomName,
        'min-timer': window.minutesLeft,
        }));


        var Minutes = 60 * {{ room.time }};
        
        display = document.querySelector('#time');
        startTimer(Minutes, display);
    }

    // function joinChat() {
    //   chatSocket.send(JSON.stringify({
    //     'command': 'chat_join',
    //     'from': username,
    //     'room': roomName,
    //   }));
      
    // }

    function createMessage(data) {
      var author = data['author'];

      var uploadedContent = document.createElement('img');
      var msgListTag = document.createElement('li');
      var imgTag = document.createElement('img');
      var pTag = document.createElement('p');

      console.log('My object: ', data);
      pTag.textContent = data.message;
      imgTag.src = 'http://emilcarlsson.se/assets/mikeross.png';
      

      uploadedContent.style.height = '300px';
      uploadedContent.style.width = '300px';
      uploadedContent.style.borderRadius = '10px';
      uploadedContent.src = data['image'];
      
      if (author === username) {
        msgListTag.className = 'replies';
      } else {
        msgListTag.className = 'sent';
      }

      if (data['image'] === "") {

        msgListTag.appendChild(imgTag);
        msgListTag.appendChild(pTag);
        document.querySelector('#chat-log').appendChild(msgListTag);
      
      } else {
        msgListTag.appendChild(imgTag);
        msgListTag.appendChild(pTag);
        msgListTag.appendChild(uploadedContent);
        document.querySelector('#chat-log').appendChild(msgListTag);

      }

    }

    function ConfirmPayment(){
      var pay = document.querySelector('#confirmationText');
      var stat = document.querySelector('#status');
      
      if (String(users[0]) == String(username)) {

        if (confirm('Are you sure you want to confirm payment?')) {
                // Action
          pay.textContent = "Payment Confirmed";
          stat.className = "jumbotron bg-primary p-1";
        } else {
                  // Do nothing!
          console.log('Thing was not saved to the database.');
        };

      } else {

        alert('You are not authorized to make that decision.');
      };

    }

    if (window.minutesLeft === 0) {
      // Chnage The button to dispute
      var time = document.querySelector("#time");
      var dispute = document.querySelector("#dispute");

      time.textContent = "Open Dispute";
      dispute.onclick = "ViewPage()";
    }

    function ViewPage() {
      window.location='www.escrowlite.org/contact/';
    }

    function CancelTrade() {
      if (confirm('Are you sure you want to cancel the trade?')) {
        // Save it!
        console.log('Trading is closing right away!');
        
        var button = document.querySelector('#cancel_trade');
        button.href = "{% url 'core:index' %}";
        button.click()
      } else {
        // Do nothing!
        console.log('Thing was not saved to the database.');
      };
    }

    function LeaveRoom() {
      window.location='www.escrowlite.org'
    }

</script>
</body>

</html>