chat/urls.py
from django.urls import path
from .views import index, room

app_name = 'chat'

urlpatterns = [
    path("", index, name="index"),
    path("<str:room_name>/", room, name="room")
]




core/urls.py
from django.urls import path, include, re_path
from .views import index, About, Contact, Terms, FAQ, Receive, Send, Banks, NewCard, NewBank, Transactions, profile, buy_request, Withdraw, sell_request, Notifications, delete_notification, detail_notification, delete_card, delete_bank

app_name = 'core'

urlpatterns = [

    path('', index, name='index'),
    path('about/', About.as_view(), name='about'),
    path('contact/', Contact.as_view(), name='contact'),
    path('terms/', Terms.as_view(), name='terms'),
    path('faq/', FAQ.as_view(), name='faq'),

    # User Profile Settings
    path('settings/', profile, name='settings'),

    # Send & Receive
    path('receive/', Receive, name='receive'),
    path('send/', Send, name='send'),
    path('transactions/', Transactions, name='transactions'),
    path('withdraw/', Withdraw, name='withdraw'),

    # Notification Session
    path('notifications/', Notifications, name='notifications'),
    re_path('^delete/(?P<pk>[0-9]+)/$', delete_notification, name='delete_notification'),
    re_path('^detail/(?P<pk>[0-9]+)/$', detail_notification, name='detail_notification'),

    # Bank Accounts
    path('linked_accounts/', Banks, name='cards&banks'),
	path('add_card/', NewCard, name='add_card'),
    re_path('^delete_card/(?P<pk>[0-9]+)/$', delete_card, name='delete_card'),
	path('add_bank/', NewBank.as_view(), name='add_bank'),
    re_path('^delete_bank/(?P<pk>[0-9]+)/$', delete_bank, name='delete_bank'),

    # Buy Bitcoin Request
    path('buy_request/', buy_request, name="buy_request"),
    path('sell_request/', sell_request, name="sell_request"),
]

escrowlite/urls.py

from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('trade/', include('trade.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
]

trade/urls.py
from django.urls import path
from .views import sellers, buyers, top_sellers, top_buyers, seller_detail, buyer_detail, open_trade

app_name = 'trade'

urlpatterns = [
    path("quick_sell/", sellers, name="sell"),
    path("quick_buy/", buyers, name="buy"),

    # Previewed Top Sellers And Buyers
    path('top_sellers/', top_sellers, name="top_sell"),
    path('top_buyers/', top_buyers, name="top_buy"),

    path('sellers/<int:pk>/', seller_detail, name="seller_detail"),
    path('buyers/<int:pk>/', buyer_detail, name="buyer_detail"),

    path('open_trade/', open_trade, name="open_trade"),
]

trade/models.py
from django.db import models
from django_countries.fields import CountryField
from core.choices import currencyChoices, paymentMethodChoices
from core.models import Account

class Seller(models.Model):
    """
    Sellers List
    """

    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    currency = models.CharField(max_length=100, choices=currencyChoices)
    min_btc = models.FloatField()
    max_btc = models.FloatField()
    rate = models.FloatField()
    method = models.CharField(max_length=250, choices=paymentMethodChoices)
    terms = models.CharField(max_length=300)
    timer = models.IntegerField()
    is_online = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} as {self.name} - {self.rate}/{self.currency}"


class Buyer(models.Model):
    """
    Buyers List
    """

    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    currency = models.CharField(max_length=100, choices=currencyChoices)
    min_btc = models.FloatField()
    max_btc = models.FloatField()
    rate = models.FloatField()
    method = models.CharField(max_length=250, choices=paymentMethodChoices)
    terms = models.CharField(max_length=300, null=True, blank=True)
    timer = models.IntegerField()
    is_online = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} as {self.name} - {self.rate}/{self.currency}"

trade/forms.py
from django import forms
from .models import Buyer, Seller
from django.contrib.auth.models import User

from django.conf import settings
from django.core.mail import send_mail

from chat.models import Room

class TradeForm(forms.Form):
    """
    Form For Opening Trade Request
    """

    amount = forms.FloatField(
        widget=forms.NumberInput(attrs={'class': 'form-row', 'oninput': 'CalculateByRateFromBtc()'}),
    )

    currency_value = forms.FloatField(
        widget=forms.NumberInput(attrs={'class': 'form-row', 'oninput': 'CalculateByRateFromCurrency()'})
    )


    def send(self, user, email, info):
        """
        Send Request To Trader
        """

        # Sending the email
        subject = f"Request From {user}"

        message = """
You Have A New Request from {0},

Your Request:
Bitcoin you wish to buy is {8}
The present value in {2} is {9}

Trader Dashboard Information:

Preferred payment method is {1}
User currency - {2}
Rate - {3}
Min & Max Purchase of Bitcoin - {4} to {5}
Instructions for trade - {6}
Predefinded time for trade - {7}

Best Regards,
Team EscrowLite
        
        """.format(
            user,
            info.method,
            info.currency,
            info.rate,
            info.min_btc,
            info.max_btc,
            info.terms,
            info.timer,
            self.cleaned_data['amount'],
            self.cleaned_data['currency_value'],
            )

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [email],
            fail_silently=True,
        )



class OpenTradeForm(forms.ModelForm):
    """
    Creating A New Websocket Room
    """

    def __init__(self, *args, **kwargs):
        
        request_choices = kwargs.pop('requests', None)
        user_choices = kwargs.pop('users', None)

        super(OpenTradeForm, self).__init__(*args, **kwargs)

        self.fields['trade_id'].choices = request_choices
        self.fields['recipient_name'].choices = user_choices

    recipient_name = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=(("--", "--")),
    )

    trade_id = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=(("--", "--")),
    )

    class Meta:
        model = Room
        fields = ['purchase_price', 'btc_price']
        widgets = {
            'purchase_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'btc_price': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def send(self, user, name, email):
        """
        Send Tade Link To User
        """

        # Sending the email
        subject = f"New Trade Initiated With {user}"

        message = f"""
A new trade window has been created for you and {user} on EscrowLite secured escrow service.

www.escrowlite/chat/{name}



Log into your escrowlite account to see more information regarding this trade - www.escrowlite.org

Happy Trading!


Best Regards,
Team EscrowLite
        
        """

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [email, user.email],
            fail_silently=True,
        )

trade/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib import messages
from django.contrib.auth.models import User

from .models import Seller, Buyer
from .forms import TradeForm, OpenTradeForm
from .generator import passkey

from chat.models import Room
from notifications.signals import notify
from random import shuffle

def sellers(request):
    """
    Sellers List Page
    """

    template = "trade/sell.html"

    currency = request.user.account.currency

    data = Seller.objects.filter(currency=currency)

    context = {
        'currency': currency,
        'data': data
    }

    return render(request, template, context)


def buyers(request):
    """
    Sellers List Page
    """

    template = "trade/buy.html"

    currency = request.user.account.currency

    data = Buyer.objects.filter(currency=currency)

    context = {
        'currency': currency,
        'data': data
    }

    return render(request, template, context)


def top_sellers(request):
    """
    List of Sellers
    """

    template = "trade/top_sell.html"

    sellers = Seller.objects.all()

    shuffle(sellers)
    context = {
        'data': sellers
    }

    return render(request, template, context)

def top_buyers(request):
    """
    List of buyers
    """

    template = "trade/top_buy.html"

    buyers = Buyer.objects.all()

    shuffle(buyers)
    context = {
        'data': buyers
    }

    return render(request, template, context)


def seller_detail(request, pk):
    """
    Displaying Seller Object
    """

    object = Seller.objects.get(pk=pk)

    if request.method == "POST":
        form = TradeForm(request.POST)

        if form.is_valid():

            form.send(user=request.user, email=object.user.user.email, info=object)

            # Notify Buyer
            notify.send(
                sender=request.user,
                recipient=object.user.user,
                verb=f"Buy Request From {request.user}",
                description="You just received a trade request from buyer. Please check your email to get information of trade."
            )

            # Notification object
            notify.send(
                sender = User.objects.first(),
                recipient = request.user,
                verb = f"You Sent A Buy Request To {object.user.user}",
                description = "Your request to buy {0} bitcoin at {1}{2}/BTC has been sent successfully. Please check your email and await further instructions on trade.".format(form.data['amount'],object.rate,object.currency),
                )

            messages.success(request, "Request Sent!")
            return redirect('core:index')
    else:
        form = TradeForm()

    context = {
        'object': object,
        'form' : form
    }

    return render(request, "trade/seller.html", context)

def buyer_detail(request, pk):
    """
    Displaying Buyer Object
    """

    object = Buyer.objects.get(pk=pk)
    form = TradeForm()

    if request.method == "POST":
        form = TradeForm(request.POST)

        if form.is_valid():

            form.send(user=request.user, email=object.user.user.email, info=object)

            # Notify Buyer
            notify.send(
                sender=request.user,
                recipient=object.user.user,
                verb=f"Sell Request From {request.user}",
                description="You just received a trade request from seller. Please check your email to get information of trade."
            )

            # Notification object
            notify.send(
                sender = User.objects.first(),
                recipient = request.user,
                verb = f"You Sent A Sell Request To {object.user.user}",
                description = "Your request to sell {0} bitcoin at {1}{2}/BTC has been sent successfully. Please check your email and await further instructions on trade.".format(form.data['amount'],object.rate,object.currency),
                )

            messages.success(request, "Request Sent!")
            return redirect('core:index')
    else:
        form = TradeForm()

    context = {
        'object': object,
        'form' : form
    }

    return render(request, "trade/buyer.html", context)


def open_trade(request):
    """
    Function To Create A New Room And Notify The Users Under It
    """

    # buy_requests = Buyer.objects.filter(name=request.user.username)
    sellersList = Seller.objects.all()
    sellers = [i.pk for i in sellersList]

    usersList = User.objects.all()
    users = [i.username for i in usersList]

    users = zip(users, users)
    requests = zip(sellers, sellers)

    if request.method == "POST":

        form = OpenTradeForm(request.POST, requests=requests, users=users)
        
        if form.is_valid():
            import pdb; pdb.set_trace()
            recipient = form.data['recipient_name']
            trade_id = form.data['trade_id']

            user = User.objects.get(username=recipient)
            sell_request = Seller.objects.get(pk=int(trade_id))
            
            name = str(passkey())

            form.send(user=request.user, name=name, email=user.email)

            chat = Room.objects.create(
                name = name,
                currency = sell_request.currency,
                purchase_price = form.data['purchase_price'],
                btc_price =  form.data['btc_price'],
                rate = sell_request.rate,
                method = sell_request.method,
                terms = sell_request.terms,
                time = sell_request.timer,
            )
            chat.save()

            # Notify Buyer
            notify.send(
                sender=request.user,
                recipient=user,
                verb=f"New Trade Started!",
                description=f"""
                    Your trade request was accepted by {request.user.username}, 
                    
                Open the live chat right now at
                
                www.escrowlite.org/chat/{name}/
                    """,
            )

            # Notification object
            notify.send(
                sender = User.objects.first(),
                recipient = request.user,
                verb = f"New Trade Started!",
                description = f"""
                    You just opened a new trade window at
                    
                    www.escrowlite.org/chat/{name}/
                    """,
                )

            messages.success(request, "Request Sent!")
            return redirect('core:index')


    form = OpenTradeForm(requests=requests, users=users)

    return render(request, "trade/create.html", {'form': form})

trade/templates/trade/buy.html
{% extends "core/index.html" %}
{% load static %}

{% block info %}


<div class="col-lg-12">

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-striped">
                    <h3><b>Available Bitcoin Buyers ({{ currency }})</b></h3>
                    <br>
                    <thead>
                        <tr>
                            <th>Buyer</th>
                            <th>Payment Method</th>
                            <th>Price / BTC</th>
                            <th>Limits</th>
                            <th>  </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for buyer in data %}
                        <tr>
                            <td>
                                {{ buyer.name }}
                                {% if buyer.is_online == True %}
                                    <img src="https://img.icons8.com/color/12/000000/ok--v1.png"/>
                                {% else %}
                                    <img src="https://img.icons8.com/material-two-tone/12/000000/ok.png"/>
                                {% endif %}
                            </td>
                            <td>{{ buyer.method }}: {{ buyer.terms }}</td>
                            <td>{{ buyer.rate }} {{ buyer.currency }}</td>
                            <td>{{ buyer.min_btc }} to {{ buyer.max_btc }} BTC</td>
                            <td><a href="{% url 'trade:buyer_detail' buyer.pk %}" ><button class="btn btn-secondary">Sell</button></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <hr>
            <a href="{% url 'core:sell_request' %}"><button class="site-btn sb-gradients">Create Custom Sell Request</button></a>
            <br>
            <hr>
            <br>
            <p><a href="{% url 'trade:top_buy' %}"><button class="site-btn sb-gradients">Top Buyers List</button></a></p>
        </div>
    </div>
</div>

{% endblock info %}

trade/templates/trade/buyer.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
	<!-- Page info section -->
	<section class="page-info-section">
	</section>
	<!-- Page info end -->



	<!-- Contact section -->
	<section class="contact-page spad">
        <div class="container jumbotron">
            <div class="row">
                <div class="col-lg-12">
                    <h3><b>Sell Bitcoins To {{ object.user }}</b></h3>
                    <p>EscrowLite user {{ object.user }} wants to buy bitcoin from you</p>
                    <div class="container">
                        <hr>
                        <h4><b>Price: </b> {{ object.rate }}{{ object.currency }}/BTC</h4>
                        <br>
                        <h4><b>Payment Method: </b> {{ object.method }}</h4>
                        <br>
                        <h4>
                            <b>User:   </b>
                            <img src="https://img.icons8.com/android/14/000000/user.png"/>
                            {{ object.name }}
                            {% if object.is_online == True %}
                                <img src="https://img.icons8.com/color/12/000000/ok--v1.png"/>
                            {% else %}
                                <img src="https://img.icons8.com/material-two-tone/12/000000/ok.png"/>
                            {% endif %}
                        </h4>
                        <br>
                        <h4><b>Trade Limits:  </b> {{ object.min_btc }} to {{ object.max_btc }} BTC</h4>
                        <br>
                        <h4><b>Payment Window:  </b> {{ object.timer }} minutes</h4>
                        <br>

                        <br>
                        <div class="jumbotron bg-light p-2">
                            <h4><b>Terms & Conditions of Trade :</b></h4>
                            <br>
                            <ul>
                                <li><h5>{{ object.terms }}</h5></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <hr>
                {% if user.is_authenticated %}
                <hr>
                <br>
                <div class="col-lg-12">
                    <h4><b>How much bitcoin do you wish to sell?</b></h4>
                    <hr>
                    <div class="col-lg-10 container p-4">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text" id="inputGroupPrepend">BTC</span>
                                    </div>
                                    {{ form.amount }}
                                    <div class="input-group-prepend">
                                      <span class="input-group-text" id="inputGroupPrepend">{{ object.currency }}</span>
                                    </div>
                                    {{ form.currency_value }}
                                    <br>
                                    <hr>
                                    <p></p>
                                </div>
                                <br>
                                <br>
                            </div>
                            <button class="site-btn sb-gradients">Proceed</button>
                        </form>
                    </div>
                </div>
                

                {% else %}
                <a href="{% url 'account_login' %}">
                    <button class="site-btn sb-gradients">Sign Up For Free</button>
                </a>
                <p>You have to be signed in to be able to initiate a trade</p>
                {% endif %}

            </div>
            <br>
            <p>Happy Trading !!</p>
        </div>
	</section>
	<!-- Contact section end -->

    <script type="text/javascript">
        function CalculateByRateFromBtc() {
            var amount = document.getElementById("id_amount").value;
            var value = {{ object.rate }};

            var result = amount * value;

            document.getElementById("id_currency_value").value = result;
            };

        function CalculateByRateFromCurrency() {
            var amount = document.querySelector("#id_currency_value").value;
            var value = {{ object.rate }};

            var result = amount / value;

            document.querySelector("#id_amount").value = result;
            }
    </script>

{% endblock %}

trade/templates/trade/create.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
	<!-- Page info section -->
	<section class="page-info-section">
	</section>
	<!-- Page info end -->



	<!-- Contact section -->
	<section class="contact-page spad">
        <div class="container jumbotron">
            <div class="row">
                <div class="col-lg-10">
                    <h3 class="text-center"><b>Create A New Chat Window For Trade</b></h3>
                    <hr>
                    <br>
                    <form action="." method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <br>
                        <br>
                        <button type="submit" class="site-btn btn-secondary sb-gradients">Start Escrow</button>
                    </form>
                </div>
            </div>
        </div>
	</section>
	<!-- Contact section end -->

    <script type="text/javascript">
        function CalculateByRateFromBtc() {
            var amount = document.getElementById("id_amount").value;
            var value = {{ object.rate }};

            var result = amount * value;

            document.getElementById("id_currency_value").value = result;
            };

        function CalculateByRateFromCurrency() {
            var amount = document.querySelector("#id_currency_value").value;
            var value = {{ object.rate }};

            var result = amount / value;

            document.querySelector("#id_amount").value = result;
            }
    </script>

{% endblock %}

trade/templates/trade/sell.html
{% extends "core/index.html" %}
{% load static %}

{% block info %}


<div class="col-lg-12">

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-striped">
                    <h3><b>Available Bitcoin Sellers ({{ currency }})</b></h3>
                    <br>
                    <thead>
                        <tr>
                            <th>Seller</th>
                            <th>Payment Method</th>
                            <th>Price / BTC</th>
                            <th>Limits</th>
                            <th>  </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for seller in data %}
                        <tr>
                            <td>
                                {{ seller.name }}
                                {% if seller.is_online == True %}
                                    <img src="https://img.icons8.com/color/12/000000/ok--v1.png"/>
                                {% else %}
                                    <img src="https://img.icons8.com/material-two-tone/12/000000/ok.png"/>
                                {% endif %}
                            </td>
                            <td>{{ seller.method }}: {{ seller.terms }}</td>
                            <td>{{ seller.rate }} {{ seller.currency }}</td>
                            <td>{{ seller.min_btc }} to {{ seller.max_btc }} BTC</td>
                            <td><a href="{% url 'trade:seller_detail' seller.pk %}" ><button class="btn btn-secondary">Buy</button></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <hr>
            <a href="{% url 'core:buy_request' %}"><button class="site-btn sb-gradients">Create Custom Buy Request</button></a>
            <br>
            <hr>
            <br>
            <p><a href="{% url 'trade:top_sell' %}"><button class="site-btn sb-gradients">Top Sellers List</button></a></p>
        </div>
    </div>
</div>

{% endblock info %}

trade/templates/trade/top_buy.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
	<!-- Page info section -->
	<section class="page-info-section">
		<div class="container">
			<div class="site-beradcamb">
				<a href="{% url 'core:index' %}">Home</a>
				<span><i class="fa fa-angle-right"></i> Best Buyers</span>
			</div>
		</div>
	</section>
	<!-- Page info end -->



	<!-- Contact section -->
	<section class="contact-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-striped">
                        <h3 class="text-center"><b>Top Bitcoin Buyers</b></h3>
                        <br>
                        <thead>
                            <tr>
                                <th>Buyer</th>
                                <th>Payment Method</th>
                                <th>Price / BTC</th>
                                <th>Limits</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for buyer in data %}
                            <tr>
                                <td>{{ buyer.name }}</td>
                                <td>{{ buyer.method }}: {{ buyer.terms }}</td>
                                <td>{{ buyer.rate }} {{ buyer.currency }}</td>
                                <td>{{ buyer.min_btc }} to {{ buyer.max_btc }} BTC</td>
                                <td><a href="{% url 'trade:buyer_detail' buyer.pk %}" ><button class="btn btn-secondary">Sell</button></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</section>
	<!-- Contact section end -->

{% endblock %}

trade/templates/trade/top_sell.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
	<!-- Page info section -->
	<section class="page-info-section">
		<div class="container">
			<div class="site-beradcamb">
				<a href="{% url 'core:index' %}">Home</a>
				<span><i class="fa fa-angle-right"></i> Best Sellers</span>
			</div>
		</div>
	</section>
	<!-- Page info end -->



	<!-- Contact section -->
	<section class="contact-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-striped">
                        <h3 class="text-center"><b>Top Bitcoin Sellers</b></h3>
                        <br>
                        <thead>
                            <tr>
                                <th>Seller</th>
                                <th>Payment Method</th>
                                <th>Price / BTC</th>
                                <th>Limits</th>
                                <th>  </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for seller in data %}
                            <tr>
                                <td>{{ seller.name }}</td>
                                <td>{{ seller.method }}: {{ seller.terms }}</td>
                                <td>{{ seller.rate }} {{ seller.currency }}</td>
                                <td>{{ seller.min_btc }} to {{ seller.max_btc }} BTC</td>
                                <td><a href="{% url 'trade:seller_detail' seller.pk %}" ><button class="btn btn-secondary">Buy</button></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</section>
	<!-- Contact section end -->

{% endblock %}