chat/urls.py
from django.urls import path
from .views import index, room

app_name = 'chat'

urlpatterns = [
    path("", index, name="index"),
    path("<str:room_name>/", room, name="room")
]




core/urls.py
from django.urls import path, include, re_path
from .views import index, About, Contact, Terms, FAQ, Receive, Send, Banks, NewCard, NewBank, Transactions, profile, buy_request, Withdraw, sell_request, Notifications, delete_notification, detail_notification, delete_card, delete_bank

app_name = 'core'

urlpatterns = [

    path('', index, name='index'),
    path('about/', About.as_view(), name='about'),
    path('contact/', Contact.as_view(), name='contact'),
    path('terms/', Terms.as_view(), name='terms'),
    path('faq/', FAQ.as_view(), name='faq'),

    # User Profile Settings
    path('settings/', profile, name='settings'),

    # Send & Receive
    path('receive/', Receive, name='receive'),
    path('send/', Send, name='send'),
    path('transactions/', Transactions, name='transactions'),
    path('withdraw/', Withdraw, name='withdraw'),

    # Notification Session
    path('notifications/', Notifications, name='notifications'),
    re_path('^delete/(?P<pk>[0-9]+)/$', delete_notification, name='delete_notification'),
    re_path('^detail/(?P<pk>[0-9]+)/$', detail_notification, name='detail_notification'),

    # Bank Accounts
    path('linked_accounts/', Banks, name='cards&banks'),
	path('add_card/', NewCard, name='add_card'),
    re_path('^delete_card/(?P<pk>[0-9]+)/$', delete_card, name='delete_card'),
	path('add_bank/', NewBank.as_view(), name='add_bank'),
    re_path('^delete_bank/(?P<pk>[0-9]+)/$', delete_bank, name='delete_bank'),

    # Buy Bitcoin Request
    path('buy_request/', buy_request, name="buy_request"),
    path('sell_request/', sell_request, name="sell_request"),
]

escrowlite/urls.py

from django.contrib import admin
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('trade/', include('trade.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
]

trade/urls.py
from django.urls import path
from .views import sellers, buyers, top_sellers, top_buyers, seller_detail, buyer_detail, open_trade

app_name = 'trade'

urlpatterns = [
    path("quick_sell/", sellers, name="sell"),
    path("quick_buy/", buyers, name="buy"),

    # Previewed Top Sellers And Buyers
    path('top_sellers/', top_sellers, name="top_sell"),
    path('top_buyers/', top_buyers, name="top_buy"),

    path('sellers/<int:pk>/', seller_detail, name="seller_detail"),
    path('buyers/<int:pk>/', buyer_detail, name="buyer_detail"),

    path('open_trade/', open_trade, name="open_trade"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

from phone_field import PhoneField
from django_countries.fields import CountryField

from .choices import monthChoices, dayChoices, currencyChoices


class Account(models.Model):
    """
    User Account Model
    """
    currency = models.CharField(default="USD", max_length=3, choices=currencyChoices)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    date_joined = models.DateTimeField(auto_now=True)
    balance = models.FloatField()
    address_id = models.CharField(max_length=100)
    country = CountryField()
    

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        """Saves complaint"""

        super(Account, self).save(*args, **kwargs)

class Transaction(models.Model):
    """
    Transactions carried out
    """

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.IntegerField()
    transaction_id = models.CharField(max_length=50)
    transaction_url = models.CharField(max_length=200)
    status = models.CharField(max_length=20)
    transaction_type = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.account.user.username} Transactions"

    def save(self, *args, **kwargs):
        """Saves complaint"""

        super(Transaction, self).save(*args, **kwargs)

class Card(models.Model):
    """
    Bank Account Model
    """

    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    account_name = models.CharField(max_length=200)
    cvv = models.IntegerField()
    expiry_month = models.CharField(max_length=20, choices=monthChoices)
    expiry_day = models.CharField(max_length=20, choices=dayChoices)
    card_number = models.IntegerField()
    pin = models.IntegerField()

    def __str__(self):
        return f'{self.user} Card'


class Bank(models.Model):
    """
    Bank Account Model
    """
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    country = CountryField()
    bank_name = models.CharField(max_length=50)
    acc_name = models.CharField(max_length=100)
    acc_number = models.IntegerField()
    ## Currency field
    ifsc_code = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.bank_name}'



class Contact(models.Model):
    """
    Contact Model
    """

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.IntegerField()
    question = models.CharField(max_length=10000)

    def __str__(self):
        return f'Message from {self.first_name} {self.last_name}!!'

    def save(self, *args, **kwargs):
        """Saves complaint"""

        super(Contact, self).save(*args, **kwargs)


    

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_save
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import CreateView, TemplateView, UpdateView, DetailView
from django.views import View
from django.views.generic.edit import FormView
from django.conf import settings

from .forms import ContactForm, CardsForm, BanksForm, CustomSignupForm, UpdateUserForm, UpdateAccountForm, BuyRequest, SendForm, WithdrawalForm, SellRequest
from .models import Contact, Card, Bank, Transaction, Account

from trade.models import Buyer, Seller

from notifications.signals import notify
from coinbase.wallet.client import Client
import json
from random import shuffle
import cryptocompare

# SETTING UP COINBASE CLIENT
client = Client(api_key=settings.API_KEY, api_secret=settings.API_SECRET)


def get_price(currency_code):
    """
    Returning the current btc price for specified currency
    """
    data = cryptocompare.get_price('BTC', curr=currency_code)
    return data['BTC'][currency_code]


def index(request):
    """Base Index Page"""

    template_name = 'core/index.html'

    buyers = Buyer.objects.all()
    shuffle(buyers)

    sellers = Seller.objects.all()
    shuffle(sellers)

    if request.user.is_authenticated == True:
        account = client.get_primary_account()
        
        try:
            person = Account.objects.get(user=request.user)

            wallet_balance = person.balance
            balance = "%.5f" % wallet_balance

            # Getting the present bitcoin value in that currency
            currency = person.currency
            price = get_price(currency)

        except Account.DoesNotExist:

            # Creating the wallet
            address = client.create_address(account.id)

            wallet_balance = 0.000
            balance = "%.5f" % wallet_balance

            Account.objects.create(
                user = request.user,
                address = address['address'],
                address_id = address['id'],
                balance = wallet_balance,
                )

            currency = "USD"
            price = get_price(currency_code=currency)
        
        currency_balance = float(price) * float(balance)
        currency_balance = "%.2f" % currency_balance
        
        context = {
            'buyers': buyers[:4],
            'seller': sellers[:4],
            'currency_balance': currency_balance,
            'currency': currency,
            'price': price,
            'balance': balance,
        }

        return render(request, template_name, context)

    context = {
        'buyers': buyers[:4],
        'sellers': sellers[:4],
    }


    return render(request, template_name, context)


class Terms(TemplateView):
    """Terms And Conditions"""
    template_name = 'core/terms.html'


class About(TemplateView):
    """About Page"""
    template_name = 'core/about.html'

class FAQ(TemplateView):
    """FAQ Page"""
    template_name = 'core/faq.html'


class Contact(CreateView):
    """Contact Us Page"""

    model = Contact
    form_class = ContactForm
    template_name = 'core/contact.html'

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST)

        if form.is_valid():

            contact = form.save()
                
            contact.save()
            contact.clean()

            messages.success(self.request, "Message Sent")

            return redirect('core:index')



@login_required
def profile(request):
    """Profile Update Page"""
    
    template = "core/dashboard.html"
    
    if request.method == "GET":

        form1 = UpdateUserForm(instance=request.user)

        form2 = UpdateAccountForm(instance=request.user.account)

        context = {
            'form1': form1,
            'form2': form2,
        }

        return render(request, template, context)

    elif request.method == "POST":

        form1 = UpdateUserForm(request.POST, instance=request.user)
        form1.save()
        form2 = UpdateAccountForm(request.POST, instance=request.user.account)
        form2.save()

        sender = User.objects.first()
        # Notification object
        notify.send(
            sender,
            recipient=request.user,
            verb="Profile Updated!",
            description="Your account profile information was just updated",
            )

        messages.success(request, "Account updated!")
        return redirect('core:index')

@login_required
def Receive(request):
    """
    Receive Bitcoin
    """
    account = Account.objects.get(user=request.user)
    address = account.address
    balance = account.balance

    # Getting the present bitcoin value in that currency
    currency = account.currency
    price = get_price(currency_code=currency)

    currency_balance = float(price) * float(balance)
    currency_balance = "%.2f" % currency_balance

    context = {
        'currency_balance': currency_balance,
        'price': price,
        'currency': currency,
        'address' : address,
        'balance' : "%.5f" % balance
    }
    return render(request, "core/receive.html", context)

@login_required
def Send(request):
    """
    Send Bitcion
    """
    template_name = "core/send.html"

    balance = Account.objects.get(user=request.user).balance

    # Getting the present bitcoin value in that currency
    currency = Account.objects.get(user=request.user).currency
    price = get_price(currency_code=currency)

    currency_balance = float(price) * float(balance)
    currency_balance = "%.2f" % currency_balance

    if request.method == "POST":

        form = SendForm(request.POST)
        
        if float(form.data['amount']) > float(balance):
            messages.info(request, "Insufficient Balance!")
            return redirect("core:send")


        sender = User.objects.first()
        # Notification object
        notify.send(
            sender,
            recipient=request.user,
            verb="Payout Request Sent!",
            description="We encountered an error while trying to send out {0} to {1}. Please try again in a few minutes and if you still face the same problems, contact support.".format(form.data['amount'], form.data['adress']),
            )

        messages.success(request, "There is an issue sending funds out! Please contact support")
        return redirect("core:index")

    form = SendForm()

    context = {
        'form': form,
        'currency_balance': currency_balance,
        'price': price,
        'currency': currency,
        'balance': "%.5f" % balance,
    }
    return render(request, template_name, context)


@login_required
def Withdraw(request):
    """
    Withdrawal Page
    """
    template_name = "core/withdraw.html"
    
    balance = Account.objects.get(user=request.user).balance

    # Getting the present bitcoin value in that currency
    currency = Account.objects.get(user=request.user).currency
    price = get_price(currency_code=currency)

    currency_balance = float(price) * float(balance)
    currency_balance = "%.2f" % currency_balance

    accounts = Bank.objects.filter(user=request.user.account)

    choices = zip(accounts, accounts)

    if request.method == "POST":
        form = WithdrawalForm(request.POST, account_choices=choices)

        if form.is_valid():

            if float(form.data['amount']) >= float(currency_balance):
                messages.info(request, "Insufficient Balance!")
                return redirect("core:withdraw")

            sender = User.objects.first()
            # Notification object
            notify.send(
                sender,
                recipient=request.user,
                verb="Withdraw Funds",
                description="There is a error in the processing of this request. Please try again!!",
                )

            messages.success(request, "Withdrawal Request Sent!")
            return redirect("core:index")
    
    else:
        form = WithdrawalForm(account_choices=choices)

    context = {
        'form': form,
        'currency_balance': currency_balance,
        'price': price,
        'currency': currency,
        'balance': "%.5f" % balance,
    }

    return render(request, template_name, context)


@login_required
def Banks(request):
    """
    Linked Banks
    """
    template_name = "core/card&bank.html"

    banks = Bank.objects.filter(user=request.user.account)
    cards = Card.objects.filter(user=request.user.account)

    balance = Account.objects.get(user=request.user).balance

    # Getting the present bitcoin value in that currency
    currency = Account.objects.get(user=request.user).currency
    price = get_price(currency)

    currency_balance = float(price) * float(balance)
    currency_balance = "%.2f" % currency_balance

    context = {
        'currency_balance': currency_balance,
        'price': price,
        'currency': currency,
        'balance': "%.5f" % balance,
        'cards': cards,
        'banks': banks,
    }

    return render(request, template_name, context)

@login_required
def NewCard(request):
    """
    Adding New Card
    """

    model = Card
    template_name = "core/add_card.html"

    if request.method == "POST":
        form = CardsForm(request.POST)
        
        if form.is_valid():

            form.save(user=request.user.account)

            sender = User.objects.first()
            # Notification object

core/templates/core/add_bank.html
{% extends 'core/index.html' %}
{% load static %}

{% block info %}

<div class="col-lg-8">

	<div class="container">
    	<div class="bg-light jumbotron">
	        <div class="creditCardForm">
	            <div class="heading">
	                <h3>Confirm Purchase</h3>
	            </div>
	            <div class="payment">
	                <form method="POST" action="{% url 'core:add_bank' %}">
                        {% csrf_token %}
	                    <div class="form-row">
	                        <label>Bank Country</label>
	                        {{ form.country }}
						</div>
						<br>
	                    <div class="form-row">
	                        <label for="bank name">Bank Name</label>
	                        {{ form.bank_name }}
	                    </div>
						<br>
						<div class="form-row">
	                        <label for="acc name">Account Name</label>
                            {{ form.acc_name }}
						</div>
						<br>
	                    <div class="form-row">
	                        <label for="acc number">Account Number</label>
                            {{ form.acc_number }}
						</div>
						<br>
	                    <div class="form-row">
	                        <label for="ifsc code">IFSC Code</label>
                            {{ form.ifsc_code }}
						</div>
						<br>
	                    <div class="form-row" id="card-number-field">
	                        <p><input type="radio" id="Confirmation" value=''> I confirm the bank details above to be correct</p>
						</div>
	                    <div class="form-row">
	                        <button type="submit" class="site-btn sb-gradients">Submit</button>
	                    </div>
	                </form>
	            </div>
        	</div>
        </div>
	</div>
</div>

{% endblock info %}

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>EscrowLite</title>
	<meta charset="UTF-8">
	<meta name="description" content="Cryptocurrency Landing Page Template">
	<meta name="keywords" content="cryptocurrency, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'core/img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'core/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'core/css/themify-icons.css' %}"/>
	<link rel="stylesheet" href="{% static 'core/css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'core/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'core/css/style.css' %}"/>

	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<script src="https://www.google.com/recaptcha/api.js" async defer></script>

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section clearfix">
		<div class="container-fluid">
			<a href="{% url 'core:index' %}" class="site-logo">
				<img src="{% static 'core/img/escrowlite.jpg' %}" alt="">
			</a>
			<div class="responsive-bar"><i class="fa fa-bars"></i></div>
			<a href="" class="user"><i class="fa fa-user"></i></a>
			{% if user.is_authenticated %}
			<a href="{% url 'account_logout' %}" class="site-btn btn-info">Log Out</a>
			<a href="{% url 'trade:sell' %}" class="site-btn">Buy bitcoins</a>
			<a href="{% url 'trade:buy' %}" class="site-btn">Sell bitcoins</a>
			<nav class="main-menu">
				<ul class="menu-list">
					<li><a href="{% url 'core:contact' %}">Help</a></li>
				</ul>
			</nav>
			{% else %}
			<a href="{% url 'account_signup' %}" class="site-btn btn-info">Sign Up Free</a>
			<a href="{% url 'account_login' %}" class="site-btn">Log In</a>
			<nav class="main-menu">
				<ul class="menu-list">
					<li><a href="{% url 'core:index' %}">Home</a></li>
					<li><a href="{% url 'core:about' %}">About</a></li>
					<li><a href="{% url 'core:faq' %}">FAQ</a></li>
					<li><a href="{% url 'core:contact' %}">Contact</a></li>
				</ul>
			</nav>
			{% endif %}
		</div>
	</header>
	
	{% block content %}
	{% endblock content %}

	<!-- Newsletter section -->
	<section class="newsletter-section gradient-bg">
		<div class="container text-white">
			<div class="row">
				<div class="col-lg-7 newsletter-text">
					<h2>Subscribe to our Newsletter</h2>
					<p>Sign up for our weekly industry updates, insider perspectives and in-depth market analysis.</p>
				</div>
				<div class="col-lg-5 col-md-8 offset-lg-0 offset-md-2">
					<form class="newsletter-form">
						<input type="text" placeholder="Enter your email">
						<button>Get Started</button>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="footer-bottom">
				<div class="row">
					<div class="col-md-6 col-lg-3 footer-widget">
						<img src="{% static 'core/img/escrow.png' %}" class="mb-4" alt="">
						<span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	Copyright &copy;<script>document.write(new Date().getFullYear());</script> EscrowLite | All rights reserved 
	<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
					</div>
					<div class="col-lg-8 text-center text-lg-right">
						<ul class="footer-nav">
							<li><a href="{% url 'core:terms' %}">Terms of Use</a></li>
							<li><a href="{% url 'core:terms' %}">Privacy Policy </a></li>
							<li><a href="">support@escrowlite.org</a></li>
							<li><a href="">(510) 747-8768</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>


	<!--====== Javascripts & Jquery ======-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'core/assets/js/jquery.payform.min.js' %}" charset="utf-8"></script>
    <script src="{% static 'core/assets/js/script.js' %}"></script>
	<script src="{% static 'core/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'core/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'core/js/main.js' %}"></script>
</body>
</html>

core/templates/core/card&bank.html
{% extends "core/index.html" %}
{% load static %}

{% block info %}


<div class="col-lg-8">

  <div class="container">

  	<!-- Cards Information -->
    <div class="bg-light jumbotron creditCardForm">
      <div class="heading" role="status">
        <h3><b>Debit/Credit Cards</b></h3>
      </div>
      <br>
      <div class="row">
        {% for card in cards %}
        <div class="bg-dark jumbotron col-lg-3 p-3 m-2">
          <a href="#"><div role="button" class="text-left">
            <img src="https://img.icons8.com/ios/25/000000/bank-card-back-side.png"/>
            <p><a>{{ card.expiry_day }}/{{ card.expiry_month }}</a></p>
            <p><b>{{ card.account_name }}</b></p>
            <a href="{% url 'core:delete_card' card.id %}"><img src="https://img.icons8.com/metro/20/000000/full-trash.png"/></a>
          </div></a>

        </div>
        {% endfor %}
        <div class="bg-secondary jumbotron col-lg-3 p-3 m-2">
          <a href="{% url 'core:add_card' %}"><div role="button" class="text-center">
            <img src="https://img.icons8.com/ios-glyphs/25/000000/add.png">
            <h4>Add New Card</h4>
          </div></a>
        </div>
      </div>
    </div>
  	<!-- Cards Information -->
  </div>

  <br>

  <div class="container">
 	  <!-- Banks Inforamtion-->
    <div class="bg-light jumbotron creditCardForm">
      <div class="heading" role="status">
        <h3><b>Bank Accounts</b></h3>
      </div>
      <br>
      <div class="row">
        {% for bank in banks %}
        <div class="bg-dark jumbotron col-lg-3 p-3 m-2">
          <a href="#"><div role="button" class="text-left">
            <img src="https://img.icons8.com/ios/25/000000/bank-building.png"/>
            <p><b>{{ bank.bank_name }} Account</b></p>
          </div></a>
          <a href="{% url 'core:delete_bank' bank.id %}"><img src="https://img.icons8.com/metro/20/000000/full-trash.png"/></a>
        </div>
        {% endfor %}
        <div class="bg-secondary jumbotron col-lg-3 p-3 m-2">
          <a href="{% url 'core:add_bank' %}"><div role="button" class="text-center">
            <img src="https://img.icons8.com/ios-glyphs/25/000000/add.png">
            <h4>Add New Account</h4>
          </div></a>
        </div>
      </div>
    </div>
    <!-- Banks Information -->


  </div>
</div>


<div class="col-lg-3">
  <div class="container">
    <div class="jumbotron bg-light text-center">
      <figure class="process-icon">
        <img src="{% static 'core/img/process-icons/1.png' %}" alt="#">
        <br>
        <br>
        <h3>{{ currency_balance }} <span>{{ currency }}</span></h3>
        <p><img src="https://img.icons8.com/color/30/000000/bitcoin--v1.png"> {{ balance }} BTC</p>
      </figure>
    </div>
  </div>
</div>

{% endblock info %}

core/templates/core/faq.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<!-- Page info section -->
<section class="page-info-section">
	<div class="container">
		<h2>FAQ</h2>
		<div class="site-beradcamb">
			<a href="{% url 'core:index' %}">Home</a>
			<span><i class="fa fa-angle-right"></i> FAQ</span>
		</div>
	</div>
</section>
<!-- Page info end -->


<!-- About section -->
<section class="about-section spad">
    <div class="container">
        <h2 class="text-center"><b>Frequently Asked Questions</b></h2>
        <br>
        <div class="jumbotron">
            <ul>
                <li onclick="ShowFunction(0)" id="qut"><h4>I lost my password. How do I get it back?</h4></li>
                <hr>
                <p style="display: none;" id="ans">> Head on to <a href="{% url 'account_reset_password' %}">Password Recovery</a></p>
                <br>

                <li onclick="ShowFunction(1)" id="qut"><h4>How do I withdraw funds from my account?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > You can withdraw funds to your local bank account. Just head on to your <a href="{% url 'core:cards&banks' %}">Linked Accounts</a> page, setup a bank account you would like to receive funds to and select 'Withdraw to Bank' from your <a href="{% url 'core:index' %}">dashboard</a>
                </p>
                <br>

                <li onclick="ShowFunction(2)" id="qut"><h4>How do I link bank account to my account?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > This operation is carried out on <a href="{% url 'core:cards&banks' %}">Linked Accounts</a> page. Ensure to enter valid card and bank information where applicable
                </p>
                <br>

                <li onclick="ShowFunction(3)" id="qut"><h4>How do I confirm the email address on my account?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > Head on to <a href="{% url 'core:settings' %}">Profile Settings</a>, click the 'Change Email Address' link. There you can add or update your primary email accounts and even resent the confirmation link.
                </p>
                <br>

                <li onclick="ShowFunction(4)" id="qut"><h4>How do I receive bitcoin?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > Receiving payment is easy. Go to <a href="{% url 'core:receive' %}">Receive Bitcoin</a> page on dashboard. Copy your receiving address or scan the QR code to receive.
                </p>
                <br>

                <li onclick="ShowFunction(5)" id="qut"><h4>How can I view my transactions history?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > All transactions history are available on the <a href="{% url 'core:transactions' %}">Transactions</a> page.
                </p>
                <br>

                <li onclick="ShowFunction(6)" id="qut"><h4>Where is my refund?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > In event where you are eligible for a refund, it will be made available to your wallet. Refund trasactions are also available on the <a href="{% url 'core:transactions' %}">Transactions</a> page and you will receive an account notificaton informing you of your refund in detail. 
                </p>
                <br>

                <li onclick="ShowFunction(7)" id="qut"><h4>How do I send bitcoin?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > Sending bitcoin is smooth, secure and easy. Head on to <a href="{% url 'core:send' %}">Send Bitcoin</a> page on dashboard.
                </p>
                <br>

                <li onclick="ShowFunction(8)" id="qut"><h4>How do I sell bitcoin?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > Goto <a href="{% url 'trade:sell' %}">Buyers List</a> page, to see available buyers in your local currency or country.
                </p>
                <br>

                <li onclick="ShowFunction(9)" id="qut"><h4>How to buy bitcoin?</h4></li>
                <hr>
                <p style="display: none;" id="ans">
                    > Goto <a href="{% url 'trade:buy' %}">Sellers List</a> page, to see available buyers in your local currency or country.
                </p>
                <br>
            </ul>

        </div>
    </div>
</section>
<!-- About section end -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.4.3.min.js" ></script>
<script>

function ShowFunction(number) {
    var x = document.querySelectorAll("#ans");

    if (x[number].style.display === "none") {
    x[number].style.display = "block";
    } else {
    x[number].style.display = "none";
    };
};
</script>



{% endblock %}